fix #2 : project
MohitGupta121/Day3-assignment-portfolio pull request #5
Opened 2023-05-14 07:57 UTC by Pranjal8989

![Screenshot (26)](https://github.com/MohitGupta121/Day3-assignment-portfolio/assets/133318834/c6473207-3e5e-48af-acc6-9cb2ccdbb3d2)
![Screenshot (27)](https://github.com/MohitGupta121/Day3-assignment-portfolio/assets/133318834/a8d29d13-9ee8-4b4e-91eb-fa503a4cc6da)

2023-05-14 07:57 UTC, Pranjal8989 commented
@MohitGupta121 PTAL. thanks

2023-05-14 19:25 UTC, MohitGupta121 requested changes
@Pranjal8989 PTAL, Please make changes and colors as per screenshot, 
Thanks.

2023-05-14 19:25 UTC, MohitGupta121 commented on project.html
> +<html lang="en">
Change this file to index.html

2023-05-15 04:30 UTC, Pranjal8989 commented
@MohitGupta121 PTAL . thanks

2024-03-07 08:39 UTC, closed without merging