fix #2 : middle_section
MohitGupta121/Day3-assignment-portfolio pull request #6
Opened 2023-05-14 07:57 UTC by rsthakur8815

![Screenshot (28)](https://github.com/MohitGupta121/Day3-assignment-portfolio/assets/133319157/76e880a4-713e-4965-a67e-83effb294f88)
![Screenshot (29)](https://github.com/MohitGupta121/Day3-assignment-portfolio/assets/133319157/15c04b7a-e16f-487b-8877-e300b6dbc705)

2023-05-14 07:57 UTC, rsthakur8815 commented
@MohitGupta121 PTAL. thanks

2023-05-14 19:23 UTC, MohitGupta121 approved these changes
@rsthakur8815 LGTM, Thanks

2023-05-14 19:26 UTC, MohitGupta121 requested changes

2023-05-14 19:26 UTC, MohitGupta121 commented on middle_section.html
> +<!DOCTYPE html>
Please change this file to index.html so that at last we combine all files.

2023-05-15 04:10 UTC, rsthakur8815 commented
@MohitGupta121 PTAL. Thanks

2024-02-06 16:20 UTC, closed without merging